[2024-10-26T06:24:55.423+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-26T06:24:55.433+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: DataPipeline.load_data manual__2024-10-26T06:24:53.007354+00:00 [queued]>
[2024-10-26T06:24:55.435+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: DataPipeline.load_data manual__2024-10-26T06:24:53.007354+00:00 [queued]>
[2024-10-26T06:24:55.435+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2024-10-26T06:24:55.440+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_data> on 2024-10-26 06:24:53.007354+00:00
[2024-10-26T06:24:55.444+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=196) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-26T06:24:55.445+0000] {standard_task_runner.py:63} INFO - Started process 198 to run task
[2024-10-26T06:24:55.445+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'DataPipeline', 'load_data', 'manual__2024-10-26T06:24:53.007354+00:00', '--job-id', '43', '--raw', '--subdir', 'DAGS_FOLDER/src/***.py', '--cfg-path', '/tmp/tmpy5sw8cim']
[2024-10-26T06:24:55.446+0000] {standard_task_runner.py:91} INFO - Job 43: Subtask load_data
[2024-10-26T06:24:55.465+0000] {task_command.py:426} INFO - Running <TaskInstance: DataPipeline.load_data manual__2024-10-26T06:24:53.007354+00:00 [running]> on host 7e8a88eeae3d
[2024-10-26T06:24:55.499+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='MLopsProjectGroup6' AIRFLOW_CTX_DAG_ID='DataPipeline' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2024-10-26T06:24:53.007354+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-26T06:24:53.007354+00:00'
[2024-10-26T06:24:55.499+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-26T06:24:55.505+0000] {LoadData.py:34} INFO - Starting data loading process
[2024-10-26T06:24:55.505+0000] {LoadData.py:35} INFO - Starting data loading process
[2024-10-26T06:24:55.506+0000] {LoadData.py:34} INFO - Using pickle file: None
[2024-10-26T06:24:55.506+0000] {LoadData.py:35} INFO - Using pickle file: None
[2024-10-26T06:24:55.506+0000] {LoadData.py:37} ERROR - Pickle file not found: None
[2024-10-26T06:24:55.506+0000] {LoadData.py:38} ERROR - Pickle file not found: None
[2024-10-26T06:24:55.506+0000] {python.py:237} INFO - Done. Returned value was: False
[2024-10-26T06:24:55.506+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-26T06:24:55.513+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=DataPipeline, task_id=load_data, run_id=manual__2024-10-26T06:24:53.007354+00:00, execution_date=20241026T062453, start_date=20241026T062455, end_date=20241026T062455
[2024-10-26T06:24:55.546+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-10-26T06:24:55.556+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-26T06:24:55.556+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
