[2024-10-26T09:12:49.442+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-26T09:12:49.451+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: DataPipeline.pre_process_data manual__2024-10-26T09:12:45.197328+00:00 [queued]>
[2024-10-26T09:12:49.454+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: DataPipeline.pre_process_data manual__2024-10-26T09:12:45.197328+00:00 [queued]>
[2024-10-26T09:12:49.455+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2024-10-26T09:12:49.460+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): pre_process_data> on 2024-10-26 09:12:45.197328+00:00
[2024-10-26T09:12:49.463+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=134) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-26T09:12:49.463+0000] {standard_task_runner.py:63} INFO - Started process 136 to run task
[2024-10-26T09:12:49.464+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'DataPipeline', 'pre_process_data', 'manual__2024-10-26T09:12:45.197328+00:00', '--job-id', '170', '--raw', '--subdir', 'DAGS_FOLDER/src/***.py', '--cfg-path', '/tmp/tmp8rnnv44z']
[2024-10-26T09:12:49.465+0000] {standard_task_runner.py:91} INFO - Job 170: Subtask pre_process_data
[2024-10-26T09:12:49.481+0000] {task_command.py:426} INFO - Running <TaskInstance: DataPipeline.pre_process_data manual__2024-10-26T09:12:45.197328+00:00 [running]> on host 558a41ea7330
[2024-10-26T09:12:49.516+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='MLopsProjectGroup6' AIRFLOW_CTX_DAG_ID='DataPipeline' AIRFLOW_CTX_TASK_ID='pre_process_data' AIRFLOW_CTX_EXECUTION_DATE='2024-10-26T09:12:45.197328+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-26T09:12:45.197328+00:00'
[2024-10-26T09:12:49.516+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-26T09:12:49.521+0000] {datatype_format.py:65} INFO - Starting data processing
[2024-10-26T09:12:49.521+0000] {datatype_format.py:66} INFO - Input file: /opt/***/data/processed/processed_data.pkl
[2024-10-26T09:12:49.527+0000] {datatype_format.py:83} INFO - Loaded data from /opt/***/data/processed/processed_data.pkl with shape (45211, 1)
[2024-10-26T09:12:49.527+0000] {datatype_format.py:33} INFO - Checking data types of the dataset.
[2024-10-26T09:12:49.529+0000] {datatype_format.py:38} INFO - Saved BEFORE conversion data type information to /opt/***/data/processed/datatype_info_before.csv
[2024-10-26T09:12:49.543+0000] {datatype_format.py:53} INFO - Saved AFTER conversion data type information to /opt/***/data/processed/datatype_info_after.csv
[2024-10-26T09:12:49.568+0000] {datatype_format.py:93} INFO - Processed data saved as pickle at /opt/***/data/processed/datatype_format_processed.pkl
[2024-10-26T09:12:49.568+0000] {datatype_format.py:95} INFO - Data processing completed successfully
[2024-10-26T09:12:49.569+0000] {outlier_handing.py:88} INFO - Starting outlier handling process
[2024-10-26T09:12:49.569+0000] {outlier_handing.py:89} INFO - Input file: /opt/***/data/processed/datatype_format_processed.pkl
[2024-10-26T09:12:49.574+0000] {outlier_handing.py:94} INFO - Loaded data from /opt/***/data/processed/datatype_format_processed.pkl with shape (45211, 1)
[2024-10-26T09:12:49.574+0000] {outlier_handing.py:56} INFO - Starting outlier handling.
[2024-10-26T09:12:49.575+0000] {outlier_handing.py:79} INFO - Outlier handling completed.
[2024-10-26T09:12:49.587+0000] {outlier_handing.py:104} INFO - Saved outlier-handled data to /opt/***/data/processed/outlier_handled_data.pkl
[2024-10-26T09:12:49.588+0000] {outlier_handing.py:106} INFO - Outlier handling process completed successfully
[2024-10-26T09:12:49.589+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-26T09:12:49.589+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/src/data_preprocessing/preprocessing_main.py", line 26, in preprocess_data
    data.to_pickle(OUTPUT_FILE_PATH, index=False)
    ^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'to_pickle'
[2024-10-26T09:12:49.597+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=DataPipeline, task_id=pre_process_data, run_id=manual__2024-10-26T09:12:45.197328+00:00, execution_date=20241026T091245, start_date=20241026T091249, end_date=20241026T091249
[2024-10-26T09:12:49.602+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 170 for task pre_process_data ('str' object has no attribute 'to_pickle'; 136)
[2024-10-26T09:12:49.647+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-10-26T09:12:49.655+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-26T09:12:49.656+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
