[2024-10-26T07:17:56.656+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-26T07:17:56.666+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: DataPipeline.load_data manual__2024-10-26T07:17:54.219016+00:00 [queued]>
[2024-10-26T07:17:56.669+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: DataPipeline.load_data manual__2024-10-26T07:17:54.219016+00:00 [queued]>
[2024-10-26T07:17:56.669+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2024-10-26T07:17:56.673+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_data> on 2024-10-26 07:17:54.219016+00:00
[2024-10-26T07:17:56.676+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=553) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-26T07:17:56.677+0000] {standard_task_runner.py:63} INFO - Started process 555 to run task
[2024-10-26T07:17:56.677+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'DataPipeline', 'load_data', 'manual__2024-10-26T07:17:54.219016+00:00', '--job-id', '87', '--raw', '--subdir', 'DAGS_FOLDER/src/***.py', '--cfg-path', '/tmp/tmpcx0hzh16']
[2024-10-26T07:17:56.679+0000] {standard_task_runner.py:91} INFO - Job 87: Subtask load_data
[2024-10-26T07:17:56.695+0000] {task_command.py:426} INFO - Running <TaskInstance: DataPipeline.load_data manual__2024-10-26T07:17:54.219016+00:00 [running]> on host 7e8a88eeae3d
[2024-10-26T07:17:56.731+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='MLopsProjectGroup6' AIRFLOW_CTX_DAG_ID='DataPipeline' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2024-10-26T07:17:54.219016+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-26T07:17:54.219016+00:00'
[2024-10-26T07:17:56.731+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-26T07:17:56.736+0000] {LoadData.py:34} INFO - Starting data loading process
[2024-10-26T07:17:56.737+0000] {LoadData.py:35} INFO - Starting data loading process
[2024-10-26T07:17:56.737+0000] {LoadData.py:34} INFO - Using pickle file: None
[2024-10-26T07:17:56.737+0000] {LoadData.py:35} INFO - Using pickle file: None
[2024-10-26T07:17:56.737+0000] {LoadData.py:37} ERROR - Pickle file not found: None
[2024-10-26T07:17:56.737+0000] {LoadData.py:38} ERROR - Pickle file not found: None
[2024-10-26T07:17:56.737+0000] {python.py:237} INFO - Done. Returned value was: False
[2024-10-26T07:17:56.738+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-26T07:17:56.745+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=DataPipeline, task_id=load_data, run_id=manual__2024-10-26T07:17:54.219016+00:00, execution_date=20241026T071754, start_date=20241026T071756, end_date=20241026T071756
[2024-10-26T07:17:56.780+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-10-26T07:17:56.794+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-26T07:17:56.795+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
