[2024-10-26T07:37:15.406+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-26T07:37:15.417+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: DataPipeline.load_data manual__2024-10-26T07:37:12.838469+00:00 [queued]>
[2024-10-26T07:37:15.421+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: DataPipeline.load_data manual__2024-10-26T07:37:12.838469+00:00 [queued]>
[2024-10-26T07:37:15.421+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2024-10-26T07:37:15.426+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_data> on 2024-10-26 07:37:12.838469+00:00
[2024-10-26T07:37:15.431+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=874) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-26T07:37:15.432+0000] {standard_task_runner.py:63} INFO - Started process 876 to run task
[2024-10-26T07:37:15.433+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'DataPipeline', 'load_data', 'manual__2024-10-26T07:37:12.838469+00:00', '--job-id', '108', '--raw', '--subdir', 'DAGS_FOLDER/src/***.py', '--cfg-path', '/tmp/tmpbws7y5c7']
[2024-10-26T07:37:15.434+0000] {standard_task_runner.py:91} INFO - Job 108: Subtask load_data
[2024-10-26T07:37:15.453+0000] {task_command.py:426} INFO - Running <TaskInstance: DataPipeline.load_data manual__2024-10-26T07:37:12.838469+00:00 [running]> on host 7e8a88eeae3d
[2024-10-26T07:37:15.489+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='MLopsProjectGroup6' AIRFLOW_CTX_DAG_ID='DataPipeline' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2024-10-26T07:37:12.838469+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-26T07:37:12.838469+00:00'
[2024-10-26T07:37:15.490+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-26T07:37:15.497+0000] {LoadData.py:34} INFO - Starting data loading process
[2024-10-26T07:37:15.498+0000] {LoadData.py:35} INFO - Starting data loading process
[2024-10-26T07:37:15.498+0000] {LoadData.py:34} INFO - Using pickle file: None
[2024-10-26T07:37:15.498+0000] {LoadData.py:35} INFO - Using pickle file: None
[2024-10-26T07:37:15.499+0000] {LoadData.py:37} ERROR - Pickle file not found: None
[2024-10-26T07:37:15.499+0000] {LoadData.py:38} ERROR - Pickle file not found: None
[2024-10-26T07:37:15.499+0000] {python.py:237} INFO - Done. Returned value was: False
[2024-10-26T07:37:15.499+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-26T07:37:15.512+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=DataPipeline, task_id=load_data, run_id=manual__2024-10-26T07:37:12.838469+00:00, execution_date=20241026T073712, start_date=20241026T073715, end_date=20241026T073715
[2024-10-26T07:37:15.529+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-10-26T07:37:15.541+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-26T07:37:15.541+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
