[2024-10-26T08:57:46.369+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-26T08:57:46.378+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: DataPipeline.load_data manual__2024-10-26T08:57:42.742063+00:00 [queued]>
[2024-10-26T08:57:46.382+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: DataPipeline.load_data manual__2024-10-26T08:57:42.742063+00:00 [queued]>
[2024-10-26T08:57:46.383+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2024-10-26T08:57:46.389+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_data> on 2024-10-26 08:57:42.742063+00:00
[2024-10-26T08:57:46.394+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=205) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-26T08:57:46.395+0000] {standard_task_runner.py:63} INFO - Started process 207 to run task
[2024-10-26T08:57:46.395+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'DataPipeline', 'load_data', 'manual__2024-10-26T08:57:42.742063+00:00', '--job-id', '150', '--raw', '--subdir', 'DAGS_FOLDER/src/***.py', '--cfg-path', '/tmp/tmpsf7abq1s']
[2024-10-26T08:57:46.398+0000] {standard_task_runner.py:91} INFO - Job 150: Subtask load_data
[2024-10-26T08:57:46.427+0000] {task_command.py:426} INFO - Running <TaskInstance: DataPipeline.load_data manual__2024-10-26T08:57:42.742063+00:00 [running]> on host 558a41ea7330
[2024-10-26T08:57:46.512+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='MLopsProjectGroup6' AIRFLOW_CTX_DAG_ID='DataPipeline' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2024-10-26T08:57:42.742063+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-26T08:57:42.742063+00:00'
[2024-10-26T08:57:46.513+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-26T08:57:46.524+0000] {LoadData.py:34} INFO - Starting data loading process
[2024-10-26T08:57:46.524+0000] {LoadData.py:35} INFO - Starting data loading process
[2024-10-26T08:57:46.525+0000] {LoadData.py:34} INFO - Using pickle file: None
[2024-10-26T08:57:46.525+0000] {LoadData.py:35} INFO - Using pickle file: None
[2024-10-26T08:57:46.525+0000] {LoadData.py:37} ERROR - Pickle file not found: None
[2024-10-26T08:57:46.525+0000] {LoadData.py:38} ERROR - Pickle file not found: None
[2024-10-26T08:57:46.527+0000] {python.py:237} INFO - Done. Returned value was: False
[2024-10-26T08:57:46.527+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-26T08:57:46.544+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=DataPipeline, task_id=load_data, run_id=manual__2024-10-26T08:57:42.742063+00:00, execution_date=20241026T085742, start_date=20241026T085746, end_date=20241026T085746
[2024-10-26T08:57:46.575+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-10-26T08:57:46.586+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-26T08:57:46.587+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
